### ISSUE TITLE
Disable screen saver during media playback

### ISSUE THREAD

**Issue by davidjwbbc** [5G-MAG/rt-5gms-media-stream-handler#30]
# Problem
We have noticed, during testing, that the screen blanks after a while if we forget to turn off the screen lock feature on the phone. This can be quite annoying when you are trying to run a demo.

# Feature request
Would it be possible to add calls to the Exoplayer view `setKeepScreenOn()` method in appropriate places to enable the player to keep the screen on during media playback and allow it to blank again once playback is finished or paused (as per the answer to https://stackoverflow.com/questions/49657683/exoplayer-2-prevent-screen-dim-on-video-playback)?

**Comment by dsilhavy** [comment]
Addressed in #32, in my test the screen stayed on for more than 10 minutes, then I stopped playback.
