### ISSUE TITLE
How to get the real consumption reporting data in Media Player

### ISSUE THREAD

**Issue by shilinding** [5G-MAG/rt-5gms-media-stream-handler#31]
# Problem description
TS26.512-h40 clause 4.7.4 only defines the conditions for consumption reporting, but I can't find how to get the real consumption reporting data in the Media Stream Handler. 

The conditions are defined as follows:

> If the consumption reporting procedure is activated, the Media Session Handler shall submit a consumption report to the 5GMSd AF when any of the following conditions occur:
> -	Start of consumption of a downlink streaming session;
> -	Stop of consumption of a downlink streaming session;
> -	Upon determining the need to report ongoing 5GMS consumption at periodic intervals determined by the `clientConsumptionReportingConfiguration.reportingInterval` property.
> -	Upon determining a location change, if the `clientConsumptionReportingConfiguration.locationReporting` property is set to True.
> -	Upon determining an access network change (e.g. unicast to eMBMS, or vice versa), if the `clientConsumptionReportingConfiguration.accessReporting` property is set to True.

**Comment by haudiobe** [comment]
@dsilhavy why did you move this one away from the standards repo?

**Comment by dsilhavy** [comment]
> @dsilhavy why did you move this one away from the standards repo?

Because from my understanding, the questions are not specification related but rather how to derive the required information from the media player
