### ISSUE TITLE
Media Stream Handler User-Agent string not to specification

### ISSUE THREAD

**Issue by rjb1000** [5G-MAG/rt-5gms-media-stream-handler#36]
# Background context

In TS 26.512 V17.6.0 (2023-06), clause 6.2.3.2.1 is amended to specify more tightly the `User-Agent` header to be included in requests at reference point M4. It has always specified that a 5GMS-specific first _product_ token should be present, but now specifies that this should be suffixed with at least the 3GPP release number.

The following examples are given to illustrate the range of flexibility:

> EXAMPLE 1: `5GMSMediaStreamHandler/17.5.0 (build2634) ExoPlayerLib/2.17.1`
> EXAMPLE 2: `5GMSMediaStreamHandler/17`

# Bug description

The current implementation of the Media Stream Handler emits the following non-compliant value:

`User-Agent: Dalvik/2.1.0 (Linux; U; Android 13; Pixel 6a Build/TQ1A.230205.002)`

# Proposed remedy

Change the `User-Agent` string to prefix the current value with the 5GMS-specified _product_ token:

`User-Agent: 5GMSMediaStreamHandler/17 Dalvik/2.1.0 (Linux; U; Android 13; Pixel 6a Build/TQ1A.230205.002)`

**Comment by dsilhavy** [comment]
While it is possible to modify the request headers of the ExoPlayer I did not find a way to preserve the original `user-agent` string that the ExoPlayer is using by default.

There exists a `Utils.getUserAgent()` method which returns a different string though: `v/1.0.1 (Linux;Android 10) AndroidXMedia3/1.0.2`

What I am generating at this point looks like this: `"5GMSMediaStreamHandler/17 v/1.0.1 (Linux;Android 10) AndroidXMedia3/1.0.2 - Android (10; SM-G960F)`. This is different from the orginal one though: `"Dalvik/2.1.0 (Linux; U; Android 10; SM-G960F Build/QP1A.190711.020)`

Current status: https://github.com/5G-MAG/rt-5gms-media-stream-handler/pull/37

**Comment by rjb1000** [comment]
Calling `Util.getUserAgent()` sounds sensible, @dsilhavy.
- `v/1.0.1 (Linux;Android 10)` - Is this your application's version number from the build file? If so, you could usefully prefix it with the name of your application, formatted as a product token string, e.g "A5GMSMediaStreamHandler/1.0.1 (Linux;Android 10)".
- `AndroidXMedia3/1.0.2 - Android (10; SM-G960F)` isn't quite valid syntax. The hyphen is the troublesome part: there should only be white space between a product token and a (bracketed) comment, so it should look like `AndroidXMedia3/1.0.2 (Android 10; SM-G960F)`.
  - Looks like you are manually building this one in `$modifiedUserAgent`, so it should be easy to fix.

**Comment by dsilhavy** [comment]
Final example string:
`5GMSMediaStreamHandler/17 A5GMSMediaStreamHandler/1.0.1 (Linux;Android 10) AndroidXMedia3/1.0.2 (Android 10; SM-G960F)`
