### ISSUE TITLE
QoE Metrics Reporting - Support for MPD Information metric

### ISSUE THREAD

**Issue by dsilhavy** [5G-MAG/rt-5gms-media-stream-handler#42]
**Feature description**
The MPD Information should be derived by the ExoPlayerListener class and included in the QoE metrics report

**Relevant specifications and corresponding sections**
* 3GPP TS 26.501 Rel-17
* 3GPP TS 26.512 Rel-17
* 3GPP TS 26.247 - clause 10.2.8

**Additional context**
XSD Definition

````xml
<xs:element name="MPDInformation" type="MpdInformationType" maxOccurs="unbounded"/>

<xs:complexType name="MpdInformationType">
    <xs:choice>
        <xs:element name="Mpdinfo" maxOccurs="unbounded" type="RepresentationType" />
    </xs:choice>
    <xs:attribute name="representationId" type="xs:string" use="required" />
    <xs:attribute name="subrepLevel" type="xs:unsignedInt" use="optional" />
    <xs:anyAttribute processContents="skip" />
</xs:complexType>
````

**Comment by dsilhavy** [comment]
Added support for `MPDInformation`, example as reported:

````xml
<QoeMetric>
    <MPDInformation representationId="V300">
        <Mpdinfo bandwidth="300000" codecs="avc1.64001e" frameRate="30.0" height="360"
            mimeType="video/mp4" width="640" />
    </MPDInformation>
    <MPDInformation representationId="A48">
        <Mpdinfo bandwidth="48000" codecs="mp4a.40.2" frameRate="-1.0" frameRate="-1"
            mimeType="audio/mp4" width="-1" />
    </MPDInformation>
</QoeMetric>
````

From the spec: _The following attributes and elements shall be present within mpdinfo if they are present for the identified representation or subrepresentation and their values shall be identical to those presented in the MPD: @bandwidth, @qualityRanking, @width, @height, @mimeType, and @codecs._

Consequently I assume it is better to omit `frameRate`, `height` and `width` for all media types except video

For reference the corresponding MPD: https://livesim.dashif.org/livesim/testpic_2s/Manifest.mpd"

**Comment by dsilhavy** [comment]
Modified/Filtered version:

````xml
<QoeMetric>
    <MPDInformation representationId="V300">
        <Mpdinfo bandwidth="300000" codecs="avc1.64001e" frameRate="30.0" height="360"
            mimeType="video/mp4" width="640" />
    </MPDInformation>
    <MPDInformation representationId="A48">
        <Mpdinfo bandwidth="48000" codecs="mp4a.40.2" mimeType="audio/mp4" />
    </MPDInformation>
</QoeMetric>
````

**Comment by rjb1000** [comment]
> Modified/Filtered version

(Just to add that I checked this for schema validity, and it was all good.)
