### ISSUE TITLE
QoE Metrics Reporting and Consumption Reporting - Final report contains data from new stream 

### ISSUE THREAD

**Issue by dsilhavy** [5G-MAG/rt-5gms-media-stream-handler#71]
## Description
When enabling consumption reporting and QoE Metrics reporting the final report that is sent before switching to a new stream contains data of the newly selected stream. This is caused by asychronous processing in the Media Session Handler and the Media Streaming Handler

## Solution
When the application selects a new stream the final consumption and QoE metrics reports shall be send to the Media Session Handler prior to issuing a switch of the source. Then once the `playbackTrigger` request by the Media Session Handler is received by the Media Stream Handler the reports have been send already.

**Comment by dsilhavy** [comment]
Fixed in https://github.com/5G-MAG/rt-5gms-media-stream-handler/commit/b56ee9527fe8aedd23ce53a9cfd4a0f375c253d3

Also refactored the code to move instantiation of the controller and messenger classes to the "root" class `MediaSessionHandlerAdapter`. Then use dependency injection to supply the messenger classes with the required controller classes.

The advantage of this architecture is that we can use interfaces and implement and inject "stubs" for uni testing classes.

**Comment by rjb1000** [comment]
One "belt and braces" recommendation here is to tag all notification event generated by the Media Stream Handler with a _media delivery session identifier_. This would alert the Media Session Handler receiving the events to the fact that the information pertains to a new media streaming session and should be bundled into a separate report.

We are adding _media delivery session identifier_ to all of the notifications in the media session handling API (M6/M11) as part of the new Rel-18 TS 26.510. It would probably be a good idea to make a symmetric addition to the methods and notifications of the media stream handling API (M7/M11) in clause 13 of TS 26.512 Rel-18.
